#!/usr/bin/env python3
"""Generate ``docs/cli-reference.md`` from the real argparse parser.

The flag table is the one piece of documentation that cannot be maintained by
hand at this size — there are forty-odd flags in eight groups, and a default
written down is a default that will eventually disagree with the code. So it
is generated, and CI re-runs this with ``--check`` to prove the committed file
still matches the parser.

The GROUPING is read back off argparse too, exactly as ``banner.py`` does, so
a new flag lands in its section without a second list to update.

    python scripts/gen-cli-docs.py            # write the file
    python scripts/gen-cli-docs.py --check    # fail if it is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from cardstream.client import stream_client, web_client  # noqa: E402
from cardstream.client.common import resolve_locator  # noqa: E402

HEADER = """# CLI reference

Every flag both commands accept, in the groups `--help` prints them in.

**This page is generated** from the argparse parser by
`scripts/gen-cli-docs.py`, and CI fails if it drifts. Edit the flag's `help=`
in `client/common.py` rather than this file.

`cardstream-web` is the superset: it carries the page flags on top of every
shared pipeline flag. Flags marked **web** are not available on
`cardstream-client`.

The defaults below are what a **bare invocation** actually uses. See
[Tuning](tuning.md) for what to change and why, and
[Locating the card](locators.md) for the two locators.

"""


def _fmt_default(action: argparse.Action, effective: dict) -> str:
    if action.option_strings and action.option_strings[0] in effective:
        value = effective[action.option_strings[0]]
    else:
        value = action.default
    if isinstance(action, argparse._StoreTrueAction | argparse._StoreFalseAction):
        return "off" if value is False else "on"
    if value is None or value == "":
        return "—"
    return f"`{value}`"


def _rows(parser: argparse.ArgumentParser, web_only: set[str], effective: dict):
    for group in parser._action_groups:
        actions = [
            a
            for a in group._group_actions
            if a.option_strings and a.dest != "help" and a.dest != "version"
        ]
        if not actions:
            continue
        yield None, group.title, group.description
        for a in actions:
            flags = ", ".join(f"`{s}`" for s in a.option_strings)
            if a.option_strings[0] in web_only:
                flags += " **web**"
            choices = ""
            if a.choices:
                choices = " Choices: " + ", ".join(f"`{c}`" for c in a.choices) + "."
            help_text = (a.help or "").replace("|", "\\|").replace("\n", " ")
            yield flags, _fmt_default(a, effective), help_text + choices


def render() -> str:
    web = web_client.build_parser()
    client = stream_client.build_parser()
    client_flags = {s for a in client._actions for s in a.option_strings}
    web_only = {
        a.option_strings[0]
        for a in web._actions
        if a.option_strings and a.option_strings[0] not in client_flags
    }

    bare = web.parse_args([])
    detector_model, segmentor_model = resolve_locator(bare)
    effective = {
        "--detector-model": detector_model,
        "--segmentor-model": segmentor_model,
    }

    out = [HEADER]
    for a, b, c in _rows(web, web_only, effective):
        if a is None:
            out.append(f"\n## {b}\n")
            if c:
                out.append(f"\n{c}\n")
            out.append("\n| Flag | Default | What it does |\n| --- | --- | --- |\n")
        else:
            out.append(f"| {a} | {b} | {c} |\n")
    out.append(
        "\n---\n\n*Generated by `scripts/gen-cli-docs.py` — do not edit by hand.*\n"
    )
    return "".join(out)


def main() -> int:
    target = ROOT / "docs" / "cli-reference.md"
    new = render()
    if "--check" in sys.argv:
        old = target.read_text(encoding="utf-8") if target.exists() else ""
        if old != new:
            print(
                f"error: {target.relative_to(ROOT)} is stale — "
                "run `python scripts/gen-cli-docs.py`",
                file=sys.stderr,
            )
            return 1
        print(f"{target.relative_to(ROOT)} is up to date")
        return 0
    target.write_text(new, encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
